# PS >= 1.7.4 FO configuration
imports:
  - { resource: ../services/sf34.yml }
  - { resource: ../services/common_front.yml }

services:
  _defaults:
    public: false

  inpost.izi.hook_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - actionObjectCartDeleteBefore: '@izi\prestashop\Hook\Common\ActionCartDeleteBefore'
        actionCartSave: '@izi\prestashop\Hook\Common\ActionCartSave'
        actionObjectInPostShipmentModelAddAfter: '@izi\prestashop\Hook\Common\ActionShipmentAddAfter'
        actionObjectInPostShipmentModelUpdateBefore: '@izi\prestashop\Hook\Common\ActionShipmentUpdateBefore'
        actionObjectInPostShipmentModelUpdateAfter: '@izi\prestashop\Hook\Common\ActionShipmentUpdateAfter'
        actionValidateOrder: '@izi\prestashop\Hook\Common\ActionValidateOrder'
        actionAjaxDieCartControllerdisplayAjaxUpdateBefore: '@izi\prestashop\Hook\Front\ActionCartControllerAjaxUpdateResponse'
        actionFrontControllerSetMedia: '@izi\prestashop\Hook\Front\ActionFrontControllerSetMedia'
        paymentOptions: '@izi\prestashop\Hook\Front\ActionGetPaymentOptions'
        displayOrderConfirmation: '@izi\prestashop\Hook\Front\DisplayOrderConfirmation'
        displayIziThankYou: '@izi\prestashop\Hook\Front\DisplayIziThankYou'
        displayPaymentReturn: '@izi\prestashop\Hook\Front\DisplayPaymentReturn'
        displayProductActions: '@izi\prestashop\Hook\Front\DisplayProductActions'
        displayProductAdditionalInfo: '@izi\prestashop\Hook\Front\DisplayProductAdditionalInfo'
        displayFooterProduct: '@izi\prestashop\Hook\Front\DisplayProductFooter'
        displayExpressCheckout: '@izi\prestashop\Hook\Front\DisplayExpressCheckout'
        displayShoppingCart: '@izi\prestashop\Hook\Front\DisplayShoppingCart'
        displayShoppingCartFooter: '@izi\prestashop\Hook\Front\DisplayShoppingCartFooter'
        displayCheckoutSummaryTop: '@izi\prestashop\Hook\Front\DisplayCheckoutSummaryTop'
        displayCustomerAccountFormTop: '@izi\prestashop\Hook\Front\DisplayCustomerAccountFormTop'
        displayCustomerLoginFormAfter: '@izi\prestashop\Hook\Front\DisplayCustomerLoginFormAfter'
        displayIziCartPreviewButton: '@izi\prestashop\Hook\Front\DisplayIziCartPreviewButton'

  inpost.izi.basket_event_handler_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - PRODUCTS_QUANTITY: '@izi\prestashop\MerchantApi\Handler\Basket\ProductsQuantityEventHandler'
        PROMO_CODES: '@izi\prestashop\MerchantApi\Handler\Basket\PromoCodesEventHandler'
        RELATED_PRODUCTS: '@izi\prestashop\MerchantApi\Handler\Basket\RelatedProductsEventHandler'

  izi\prestashop\CommandBus:
    class: izi\prestashop\CommandBus
    arguments:
      - '@inpost.izi.command_handler_locator'

  inpost.izi.command_handler_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - izi\prestashop\Command\BindBasketCommand: '@izi\prestashop\Handler\BindBasketHandlerInterface'
        izi\prestashop\Command\GenerateDeepLinkCommand: '@izi\prestashop\Handler\GenerateDeepLinkHandlerInterface'
        izi\prestashop\Command\UnbindBasketCommand: '@izi\prestashop\Handler\UnbindBasketHandlerInterface'
        izi\prestashop\Command\UpdateOrderTrackingNumbersCommand: '@izi\prestashop\Handler\UpdateOrderTrackingNumbersHandlerInterface'
        izi\prestashop\Command\GetClientDetailsCommand: '@izi\prestashop\Handler\GetClientDetailsHandlerInterface'
        izi\prestashop\Command\UpdateBasketCommand: '@izi\prestashop\Handler\UpdateBasketHandlerInterface'
        izi\prestashop\Command\GetBindingConfirmationCommand: '@izi\prestashop\Handler\GetBindingConfirmationHandlerInterface'
        izi\prestashop\Command\GetOrderEventsCommand: '@izi\prestashop\Handler\GetOrderEventsHandlerInterface'
        izi\prestashop\MerchantApi\Command\ConfirmBasketBindingCommand: '@izi\prestashop\MerchantApi\Handler\ConfirmBasketBindingHandlerInterface'
        izi\prestashop\MerchantApi\Command\DeleteBasketBindingCommand: '@izi\prestashop\MerchantApi\Handler\DeleteBasketBindingHandlerInterface'
        izi\prestashop\MerchantApi\Command\GetBasketCommand: '@izi\prestashop\MerchantApi\Handler\GetBasketHandlerInterface'
        izi\prestashop\MerchantApi\Command\UpdateBasketCommand: '@izi\prestashop\MerchantApi\Handler\UpdateBasketHandlerInterface'
        izi\prestashop\MerchantApi\Command\UpdateOrderCommand: '@izi\prestashop\MerchantApi\Handler\UpdateOrderHandlerInterface'
