imports:
  - { resource: common/analytics.yml }
  - { resource: common/basket_app.yml }
  - { resource: common/cache.yml }
  - { resource: common/cart.yml }
  - { resource: common/command_bus.yml }
  - { resource: common/command_bus.php, ignore_errors: true }
  - { resource: common/configuration.yml }
  - { resource: common/context.yml }
  - { resource: common/database.yml }
  - { resource: common/environment.yml }
  - { resource: common/event_dispatcher.yml }
  - { resource: common/hook.yml }
  - { resource: common/hot_product.yml }
  - { resource: common/http.yml }
  - { resource: common/logger.yml }
  - { resource: common/logger.php, ignore_errors: true }
  - { resource: common/module.yml }
  - { resource: common/object_model.yml }
  - { resource: common/object_model.php, ignore_errors: true }
  - { resource: common/order.yml }
  - { resource: common/product.yml }
  - { resource: common/promo.yml }
  - { resource: common/security.yml }
  - { resource: common/serializer.yml }
  - { resource: common/translation.yml }
  - { resource: common/translation.php, ignore_errors: true }
  - { resource: common/shipping.yml }
  - { resource: common/templating.yml }
  - { resource: common/validator.yml }
  - { resource: common/validator.php, ignore_errors: true }
  - { resource: custom/common.yml, ignore_errors: true }

parameters:
  inpost.izi.container_version: '3.1.0'

services:
  _defaults:
    public: false

  inpost.izi.module:
    class: InPostIzi
    factory: [ Module, getInstanceByName ]
    arguments:
      - inpostizi

  inpost.izi.clock:
    class: Psr\Clock\ClockInterface
    factory: [ izi\prestashop\Clock\SystemClock, fromSystemTimezone ]

  inpost.izi.request_stack:
    class: Symfony\Component\HttpFoundation\RequestStack
    factory: [ '@inpost.izi.module', getRequestStack ]

  izi\prestashop\Repository\BasketSessionRepository:
    class: izi\prestashop\Repository\BasketSessionRepository
    arguments:
      - '@inpost.izi.serializer'
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\Payment\PaymentCurrencyChecker:
    class: izi\prestashop\Payment\PaymentCurrencyChecker

  izi\prestashop\Currency\PriceConverterInterface: '@izi\prestashop\Currency\PriceConverter'
  izi\prestashop\Currency\PriceConverter:
    class: izi\prestashop\Currency\PriceConverter
    arguments:
      - '@izi\prestashop\ObjectModel\Repository\CurrencyRepository'
      - '@izi\prestashop\Configuration\PrestaShopConfiguration'
