# common FO/BO configuration
parameters:
  inpost.izi.logger_config:
    type: rotating_file
    path: '%inpost.izi.logs_dir%/izi.log'
    max_files: 14
    bubble: false
    channels: [ general, basket_app, merchant_api ]
    process_psr_3_messages:
      remove_used_context_fields: true
    include_stacktraces: true

services:
  inpost.izi.module:
    class: InPostIzi
    public: false
    factory: [ Module, getInstanceByName ]
    arguments:
      - inpostizi

  inpost.izi.db:
    class: Db
    public: false
    factory: [ Db, getInstance ]

  inpost.izi.context:
    class: Context
    public: false
    factory: [ Context, getContext ]

  inpost.izi.clock:
    class: Psr\Clock\ClockInterface
    public: false
    factory: [ izi\prestashop\Clock\SystemClock, fromSystemTimezone ]

  inpost.izi.serializer:
    class: Symfony\Component\Serializer\SerializerInterface
    public: false
    factory: [ izi\prestashop\Serializer\SerializerFactory, create ]

  izi\prestashop\CommandBusInterface:
    alias: izi\prestashop\CommandBus
    public: true

  izi\prestashop\Hook\HookExecutorInterface:
    alias: izi\prestashop\Hook\HookExecutor
    public: true

  izi\prestashop\Hook\HookExecutor:
    class: izi\prestashop\Hook\HookExecutor
    arguments:
      - '@inpost.izi.hook_locator'
      - '@inpost.izi.module'

  inpost.izi.psr17_factory:
    class: Nyholm\Psr7\Factory\Psr17Factory
    public: false

  izi\prestashop\Http\Client\Factory\GuzzleClientFactory:
    class: izi\prestashop\Http\Client\Factory\GuzzleClientFactory

  inpost.izi.http_client.basket_app:
    class: Psr\Http\Client\ClientInterface
    factory: [ '@izi\prestashop\Http\Client\Factory\GuzzleClientFactory', create ]

  inpost.izi.http_client.basket_app.authorizing:
    class: izi\prestashop\Http\Client\AuthorizingClient
    public: false
    decorates: inpost.izi.http_client.basket_app
    arguments:
      - '@inpost.izi.http_client.basket_app.authorizing.inner'
      - '@inpost.izi.oauth2.auth_provider'

  inpost.izi.http_client.basket_app.logging:
    class: izi\prestashop\Http\Client\LoggingClient
    public: false
    decorates: inpost.izi.http_client.basket_app
    arguments:
      - '@inpost.izi.http_client.basket_app.logging.inner'
      - '@inpost.izi.basket_app_logger'

  izi\prestashop\BasketApp\BasketAppClientInterface:
    alias: izi\prestashop\BasketApp\BasketAppClient
    public: true

  izi\prestashop\BasketApp\BasketAppClient:
    class: izi\prestashop\BasketApp\BasketAppClient
    public: false
    arguments:
      - '@inpost.izi.http_client.basket_app'
      - '@inpost.izi.psr17_factory'
      - '@inpost.izi.psr17_factory'
      - '@inpost.izi.serializer'
      - '@=service("inpost.izi.environment").getBasketAppApiUri()'

  izi\prestashop\Configuration\Adapter\Configuration:
    class: izi\prestashop\Configuration\Adapter\Configuration
    public: false
    arguments:
      - '@inpost.izi.db'

  izi\prestashop\Configuration\ApiConfigurationInterface: '@izi\prestashop\Configuration\ApiConfiguration'
  izi\prestashop\Configuration\ApiConfiguration:
    class: izi\prestashop\Configuration\ApiConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@inpost.izi.serializer'

  izi\prestashop\Configuration\OrdersConfigurationInterface: '@izi\prestashop\Configuration\OrdersConfiguration'
  izi\prestashop\Configuration\OrdersConfiguration:
    class: izi\prestashop\Configuration\OrdersConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'

  izi\prestashop\Configuration\GeneralConfigurationInterface: '@izi\prestashop\Configuration\GeneralConfiguration'
  izi\prestashop\Configuration\GeneralConfiguration:
    class: izi\prestashop\Configuration\GeneralConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'

  izi\prestashop\Configuration\ShippingCourierConfigurationInterface: '@izi\prestashop\Configuration\ShippingCourierConfiguration'
  izi\prestashop\Configuration\ShippingCourierConfiguration:
    class: izi\prestashop\Configuration\ShippingCourierConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'
      - '@izi\prestashop\Configuration\Factory\DayFactory'
      - '@izi\prestashop\Configuration\Factory\HourFactory'

  izi\prestashop\Configuration\ShippingAmpConfigurationInterface: '@izi\prestashop\Configuration\ShippingAmpConfiguration'
  izi\prestashop\Configuration\ShippingAmpConfiguration:
    class: izi\prestashop\Configuration\ShippingAmpConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'
      - '@izi\prestashop\Configuration\Factory\DayFactory'
      - '@izi\prestashop\Configuration\Factory\HourFactory'

  izi\prestashop\Configuration\ConsentsConfigurationInterface: '@izi\prestashop\Configuration\ConsentsConfiguration'
  izi\prestashop\Configuration\ConsentsConfiguration:
    class: izi\prestashop\Configuration\ConsentsConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@inpost.izi.serializer'

  izi\prestashop\Configuration\GuiConfigurationInterface: '@izi\prestashop\Configuration\GuiConfiguration'
  izi\prestashop\Configuration\GuiConfiguration:
    class: izi\prestashop\Configuration\GuiConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@inpost.izi.serializer'

  izi\prestashop\Configuration\AdvancedConfigurationInterface: '@izi\prestashop\Configuration\AdvancedConfiguration'
  izi\prestashop\Configuration\AdvancedConfiguration:
    class: izi\prestashop\Configuration\AdvancedConfiguration
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'

  inpost.izi.environment:
    class: izi\prestashop\Environment\EnvironmentInterface
    public: false
    factory: [ '@izi\prestashop\Configuration\ApiConfiguration', getEnvironment ]

  izi\prestashop\Environment\AuthServerUriCollection:
    class: izi\prestashop\Environment\AuthServerUriCollection
    public: false
    arguments:
      - '@inpost.izi.environment'

  inpost.izi.oauth2.auth_provider:
    class: izi\prestashop\OAuth2\LazyAuthorizationProvider
    public: false
    arguments:
      - '@izi\prestashop\BasketApp\AuthorizationProviderFactory'
      - '@izi\prestashop\Environment\AuthServerUriCollection'
      - '@izi\prestashop\Configuration\ApiConfiguration'
      - '@izi\prestashop\Configuration\ApiConfiguration'

  izi\prestashop\BasketApp\AuthorizationProviderFactory:
    class: izi\prestashop\BasketApp\AuthorizationProviderFactory
    public: false
    arguments:
      - '@inpost.izi.psr17_factory'
      - '@inpost.izi.psr17_factory'
      - '@izi\prestashop\Http\Client\Factory\GuzzleClientFactory'

  izi\prestashop\Log\MonologLoggerFactory:
    class: izi\prestashop\Log\MonologLoggerFactory
    public: false
    arguments:
      -
        - '@izi\prestashop\Log\Handler\RotatingFileHandlerFactory'

  izi\prestashop\Log\Handler\RotatingFileHandlerFactory:
    class: izi\prestashop\Log\Handler\RotatingFileHandlerFactory
    public: false
    arguments:
      - '%kernel.environment%'

  inpost.izi.basket_app_logger:
    class: Psr\Log\LoggerInterface
    public: false
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - basket_app
      - '%inpost.izi.logger_config%'

  inpost.izi.merchant_api_logger:
    class: Psr\Log\LoggerInterface
    public: true #todo
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - merchant_api
      - '%inpost.izi.logger_config%'

  inpost.izi.general_logger:
    class: Psr\Log\LoggerInterface
    public: true
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - general
      - '%inpost.izi.logger_config%'

  izi\prestashop\Handler\UpdateOrderTrackingNumbersHandlerInterface: '@izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler'
  izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler:
    class: izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Order\OrderEventBuilderFactory'
      - '@izi\prestashop\BasketApp\BasketAppClientInterface'
      - !tagged inpost.izi.tracking_number_provider

  izi\prestashop\Handler\GetClientDetailsHandlerInterface: '@izi\prestashop\Handler\GetClientDetailsHandler'
  izi\prestashop\Handler\GetClientDetailsHandler:
    class: izi\prestashop\Handler\GetClientDetailsHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\BasketApp\BasketAppClientInterface'

  izi\prestashop\Handler\UpdateBasketHandlerInterface: '@izi\prestashop\Handler\UpdateBasketHandler'
  izi\prestashop\Handler\UpdateBasketHandler:
    class: izi\prestashop\Handler\UpdateBasketHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Basket\BasketBuilderFactory'
      - '@izi\prestashop\BasketApp\BasketAppClientInterface'
      - '@inpost.izi.general_logger'

  izi\prestashop\Shipping\CarrierModuleTrackingNumberProvider:
    class: izi\prestashop\Shipping\CarrierModuleTrackingNumberProvider
    public: false
    tags:
      - { name: inpost.izi.tracking_number_provider }
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\Builder\Order\OrderEventBuilderFactory:
    class: izi\prestashop\Builder\Order\OrderEventBuilderFactory
    public: false
    arguments:
      - '@inpost.izi.object_model.order_repository'
      - '@izi\prestashop\Builder\Order\OrderStatusDescriptionProvider'
      - '@inpost.izi.clock'

  izi\prestashop\Builder\Order\OrderStatusDescriptionProvider:
    class: izi\prestashop\Builder\Order\OrderStatusDescriptionProvider
    public: false
    arguments:
      - '@inpost.izi.object_model.order_state_repository'
      - '@izi\prestashop\Configuration\OrdersConfiguration'

  izi\prestashop\ObjectModel\Connection:
    class: izi\prestashop\ObjectModel\Connection
    public: true
    arguments:
      - '@inpost.izi.db'

  izi\prestashop\ObjectModel\Hydrator:
    class: izi\prestashop\ObjectModel\Hydrator
    public: false

  izi\prestashop\ObjectModel\ObjectManagerInterface:
    alias: izi\prestashop\ObjectModel\ObjectManager
    public: true

  izi\prestashop\ObjectModel\ObjectManager:
    class: izi\prestashop\ObjectModel\ObjectManager
    public: true
    arguments:
      - '@izi\prestashop\ObjectModel\Connection'
      - '@izi\prestashop\ObjectModel\Repository\ObjectRepositoryFactory'
      - '@izi\prestashop\ObjectModel\Hydrator'

  izi\prestashop\ObjectModel\Repository\ObjectRepositoryFactory:
    class: izi\prestashop\ObjectModel\Repository\ObjectRepositoryFactory
    public: false
    arguments:
      - '@inpost.izi.repository_locator'

  izi\prestashop\ObjectModel\Repository\CmsPageRepository:
    class: izi\prestashop\ObjectModel\Repository\CmsPageRepository
    public: false
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\ObjectModel\Repository\CurrencyRepository:
    class: izi\prestashop\ObjectModel\Repository\CurrencyRepository
    public: false
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\ObjectModel\Repository\CarrierRepository:
    class: izi\prestashop\ObjectModel\Repository\CarrierRepository
    public: false
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\ObjectModel\Repository\ShipmentRepository:
    class: izi\prestashop\ObjectModel\Repository\ShipmentRepository
    public: false
    tags:
      - { name: inpost.izi.model_repository, model_class: InPostShipmentModel }
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  inpost.izi.object_model.order_repository:
    class: izi\prestashop\ObjectModel\Repository\ObjectRepository
    public: false
    tags:
      - { name: inpost.izi.model_repository, model_class: Order }
    arguments:
      - Order
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  inpost.izi.object_model.order_state_repository:
    class: izi\prestashop\ObjectModel\Repository\ObjectRepository
    public: false
    tags:
      - { name: inpost.izi.model_repository, model_class: OrderState }
    arguments:
      - OrderState
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  inpost.izi.object_model.cart_repository:
    class: izi\prestashop\ObjectModel\Repository\ObjectRepository
    public: false
    tags:
      - { name: inpost.izi.model_repository, model_class: Cart }
    arguments:
      - Cart
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\Repository\BasketSessionRepository:
    class: izi\prestashop\Repository\BasketSessionRepository
    public: false
    arguments:
      - '@inpost.izi.serializer'
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\Hook\Common\ActionCartDeleteBefore:
    class: izi\prestashop\Hook\Common\ActionCartDeleteBefore
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@izi\prestashop\CommandBusInterface'

  izi\prestashop\Hook\Common\ActionCartSave:
    class: izi\prestashop\Hook\Common\ActionCartSave
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.module'
      - '@inpost.izi.context'
      - '@izi\prestashop\Event\EventDispatcherInterface'

  # for whatever reason Sf 3.4 might try and fail to autowire this service in the admin container
  izi\prestashop\Hook\Front\ActionCartControllerAjaxUpdateResponse:
    class: izi\prestashop\Hook\Front\ActionCartControllerAjaxUpdateResponse
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Event\EventDispatcherInterface'

  izi\prestashop\Hook\Common\ActionShipmentAddAfter:
    class: izi\prestashop\Hook\Common\ActionShipmentAddAfter
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@izi\prestashop\Event\EventDispatcherInterface'

  izi\prestashop\Hook\Common\ActionShipmentUpdateBefore:
    class: izi\prestashop\Hook\Common\ActionShipmentUpdateBefore
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@izi\prestashop\Event\EventDispatcherInterface'

  izi\prestashop\Hook\Common\ActionShipmentUpdateAfter:
    class: izi\prestashop\Hook\Common\ActionShipmentUpdateAfter
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@izi\prestashop\Event\EventDispatcherInterface'

  izi\prestashop\Hook\Common\ActionValidateOrder:
    class: izi\prestashop\Hook\Common\ActionValidateOrder
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.module'
      - '@izi\prestashop\CommandBusInterface'

  izi\prestashop\EventListener\ShipmentListener:
    class: izi\prestashop\EventListener\ShipmentListener
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@izi\prestashop\Configuration\ApiConfiguration'
      - '@izi\prestashop\ObjectModel\Repository\ShipmentRepository'
      - '@izi\prestashop\CommandBusInterface'

  izi\prestashop\Payment\PaymentCurrencyChecker:
    class: izi\prestashop\Payment\PaymentCurrencyChecker
    public: false

  izi\prestashop\EventListener\CartListener:
    class: izi\prestashop\EventListener\CartListener
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@izi\prestashop\Configuration\ApiConfiguration'
      - '@inpost.izi.context'
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\CommandBusInterface'
      - '@inpost.izi.general_logger'

  izi\prestashop\View\Templating\RendererInterface: '@izi\prestashop\View\Templating\SmartyRenderer'
  izi\prestashop\View\Templating\SmartyRenderer:
    class: izi\prestashop\View\Templating\SmartyRenderer
    public: false
    arguments:
      - '@=service("inpost.izi.context").smarty'

  izi\prestashop\ContextManager:
    class: izi\prestashop\ContextManager
    public: false
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\Hook\WidgetConfigurationResolver:
    class: izi\prestashop\Hook\WidgetConfigurationResolver
    public: true
    arguments:
      - '@izi\prestashop\Configuration\ApiConfiguration'
      - '@inpost.izi.module'
      - '@inpost.izi.context'
      - '@izi\prestashop\Payment\PaymentCurrencyChecker'
      - '@izi\prestashop\CommandBusInterface'

  izi\prestashop\Hook\WidgetRenderer:
    class: izi\prestashop\Hook\WidgetRenderer
    public: true
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Configuration\GeneralConfiguration'
      - '@izi\prestashop\View\Templating\RendererInterface'

  izi\prestashop\Builder\Basket\BasketBuilderFactory:
    class: izi\prestashop\Builder\Basket\BasketBuilderFactory
    public: false
    arguments:
      - '@inpost.izi.clock'
      - '@izi\prestashop\ContextManager'
      - '@izi\prestashop\Configuration\ConsentsConfiguration'

  izi\prestashop\Cache\ConfigurationCache:
    class: izi\prestashop\Cache\ConfigurationCache
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@inpost.izi.serializer'
      - '@inpost.izi.clock'

  izi\prestashop\Event\EventDispatcherInterface:
    alias: izi\prestashop\Event\Adapter\EventDispatcher
    public: true

  izi\prestashop\Event\Adapter\EventDispatcher:
    class: izi\prestashop\Event\Adapter\EventDispatcher
    public: false
    arguments:
      - '@inpost.izi.event_dispatcher'

  izi\prestashop\Configuration\Factory\DayFactoryInterface: '@izi\prestashop\Configuration\Factory\DayFactory'
  izi\prestashop\Configuration\Factory\DayFactory:
    class: izi\prestashop\Configuration\Factory\DayFactory
    bind:
      $module: '@inpost.izi.module'

  izi\prestashop\Configuration\Factory\HourFactoryInterface: '@izi\prestashop\Configuration\Factory\HourFactory'
  izi\prestashop\Configuration\Factory\HourFactory:
    class: izi\prestashop\Configuration\Factory\HourFactory
