# common BO configuration
imports:
  - { resource: admin/form.yml }
  - { resource: admin/form.php, ignore_errors: true }

services:
  izi\prestashop\View\Asset\AssetManagerInterface: '@izi\prestashop\View\Asset\AdminAssetManager'
  izi\prestashop\View\Asset\AdminAssetManager:
    class: izi\prestashop\View\Asset\AdminAssetManager
    public: false
    arguments:
      - '@inpost.izi.module'
      - '@inpost.izi.context'

  izi\prestashop\View\Asset\Provider\Admin\CartRulesAssetsProvider:
    class: izi\prestashop\View\Asset\Provider\Admin\CartRulesAssetsProvider
    public: false
    tags:
      - { name: inpost.izi.admin_assets_provider }
    arguments:
      - '@inpost.izi.context'
      - '@inpost.izi.request_stack'

  izi\prestashop\Handler\Config\UpdateCartRuleOptionsHandlerInterface: '@izi\prestashop\Handler\Config\UpdateCartRuleOptionsHandler'
  izi\prestashop\Handler\Config\UpdateCartRuleOptionsHandler:
    class: izi\prestashop\Handler\Config\UpdateCartRuleOptionsHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\PromoCode\CartRuleOptionsRepositoryInterface'

  izi\prestashop\ProductOptions\MessageHandler\UpdateProductOptionsHandlerInterface: '@izi\prestashop\ProductOptions\MessageHandler\UpdateProductOptionsHandler'
  izi\prestashop\ProductOptions\MessageHandler\UpdateProductOptionsHandler:
    class: izi\prestashop\ProductOptions\MessageHandler\UpdateProductOptionsHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\ProductOptions\ProductOptionsRepositoryInterface'

  izi\prestashop\Form\Type\CartRuleOptionsType:
    class: izi\prestashop\Form\Type\CartRuleOptionsType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'

  izi\prestashop\Form\Type\ObjectModelType:
    class: izi\prestashop\Form\Type\ObjectModelType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'
      - '@inpost.izi.context'

  izi\prestashop\Form\Type\EnumType:
    class: izi\prestashop\Form\Type\EnumType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'

  izi\prestashop\ProductOptions\Form\ProductOptionsType:
    class: izi\prestashop\ProductOptions\Form\ProductOptionsType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\Configuration\ProductConfigurationInterface'
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'

  izi\prestashop\Hook\Legacy\Admin\Product\ProductOptionsFormRenderer:
    class: izi\prestashop\Hook\Legacy\Admin\Product\ProductOptionsFormRenderer
    public: false
    arguments:
      - '@izi\prestashop\ProductOptions\ProductOptionsRepositoryInterface'
      - '@inpost.izi.form_factory'
      - '@izi\prestashop\View\Templating\RendererInterface'
