stages:
  - build

build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - apk update && apk add make zip
  script:
    - make build-zip-prod
  artifacts:
    name: $CI_PROJECT_NAME
    expire_in: 30 min
    paths:
      - $CI_PROJECT_NAME.zip
  rules:
    - if: $CI_COMMIT_BRANCH != 'master'
      when: manual
