services:
  php:
    image: phpdockerio/php72-cli
    volumes:
      - ./:/var/www/html/modules/inpostizi
    working_dir: /var/www/html/modules/inpostizi
    environment:
      _PS_ROOT_DIR_: /var/www/html
