security:
  providers:
    employee_provider:
      id: inpost.izi.employee_user_provider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    admin:
      pattern: ^/
      stateless: true
      guard:
        provider: employee_provider
        authenticators:
          - izi\prestashop\Security\EmployeeAuthenticator
