imports:
  - { resource: packages/ }

parameters:
  container.autowiring.strict_mode: true
  twig.ps_form_theme: bootstrap_4_horizontal_layout.html.twig
  inpost.izi.cache_dir: '%kernel.cache_dir%'

services:
  PrestaShopBundle\Twig\LayoutExtension:
    class: PrestaShopBundle\Twig\LayoutExtension
    public: false
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'
      - '%kernel.environment%'
    tags:
      - { name: twig.extension }

  PrestaShop\PrestaShop\Adapter\LegacyContext:
    class: PrestaShop\PrestaShop\Adapter\LegacyContext
    public: false

  Twig\Extension\StringLoaderExtension:
    class: Twig_Extension_StringLoader
    public: false
    tags:
      - { name: twig.extension }

  PrestaShopBundle\Twig\DataFormatterExtension:
    class: PrestaShopBundle\Twig\DataFormatterExtension
    public: false
    tags:
      - { name: twig.extension }

  izi\prestashop\Routing\AdminUrlGenerator:
    class: izi\prestashop\Routing\AdminUrlGenerator
    public: false
    decorates: router
    arguments:
      - '@izi\prestashop\Routing\AdminUrlGenerator.inner'
      - '@request_stack'

  izi\prestashop\Routing\AnnotationDirectoryLoader:
    class: izi\prestashop\Routing\AnnotationDirectoryLoader
    public: false
    decorates: sensio_framework_extra.routing.loader.annot_dir
    decoration_on_invalid: ignore
    arguments:
      - '@izi\prestashop\Routing\AnnotationDirectoryLoader.inner'

  PrestaShopBundle\EventListener\UserLocaleListener:
    class: PrestaShopBundle\EventListener\UserLocaleListener
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 15 }

  izi\prestashop\Translation\DomainNormalizingTranslator:
    class: izi\prestashop\Translation\DomainNormalizingTranslator
    public: false
    decorates: translator
    arguments:
      - '@izi\prestashop\Translation\DomainNormalizingTranslator.inner'

  izi\prestashop\Form\Type\Compatibility\CategoryChoiceTreeType:
    class: izi\prestashop\Form\Type\Compatibility\CategoryChoiceTreeType
    tags:
      - { name: form.type }
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Category\CategoryDataProvider'

  PrestaShop\PrestaShop\Adapter\Category\CategoryDataProvider:
    class: PrestaShop\PrestaShop\Adapter\Category\CategoryDataProvider
    public: false
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'

  izi\prestashop\Security\EmployeeAuthenticator:
    class: izi\prestashop\Security\EmployeeAuthenticator
    arguments:
      - '@inpost.izi.context'

  prestashop.security.admin.provider:
    class: Symfony\Component\Security\Core\User\UserProviderInterface
    synthetic: true

  inpost.izi.employee_user_provider:
    class: izi\prestashop\Security\LazyUserProvider
    arguments:
      - '@service_container'
      - prestashop.security.admin.provider

  PrestaShopBundle\Security\Voter\PageVoter:
    class: PrestaShopBundle\Security\Voter\PageVoter
    public: false
    tags:
      - { name: security.voter }

  prestashop.module.manager:
    class: PrestaShop\PrestaShop\Core\Addon\AddonManagerInterface
    synthetic: true