parameters:
  twig.ps_form_theme: bootstrap_3_horizontal_layout.html.twig
  inpost.izi.cache_dir: '%kernel.cache_dir%'

services:
  Symfony\Component\Routing\Generator\UrlGeneratorInterface: '@router'

  izi\prestashop\Routing\AnnotationDirectoryLoader:
    class: izi\prestashop\Routing\AnnotationDirectoryLoader
    public: false
    decorates: sensio_framework_extra.routing.loader.annot_dir
    arguments:
      - '@izi\prestashop\Routing\AnnotationDirectoryLoader.inner'

  izi\prestashop\HttpKernel\ServiceParamConverter:
    class: izi\prestashop\HttpKernel\ServiceParamConverter
    public: false
    tags:
      - { name: request.param_converter, converter: service }
    arguments:
      - '@service_container'

  izi\prestashop\Controller\Admin\ConfigurationController:
    class: izi\prestashop\Controller\Admin\ConfigurationController
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'
      - !tagged inpost.izi.config_initializer
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '%kernel.debug%'
    calls:
      - { method: setContainer, arguments: [ '@service_container' ] }
      - { method: setLogger, arguments: [ '@inpost.izi.general_logger' ] }

  izi\prestashop\Controller\Admin\HotProductController:
    class: izi\prestashop\Controller\Admin\HotProductController
    arguments:
      - '@inpost.izi.shop_context'
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - !tagged inpost.izi.config_initializer
      - '%kernel.debug%'
    calls:
      - { method: setContainer, arguments: [ '@service_container' ] }
      - { method: setLogger, arguments: [ '@inpost.izi.general_logger' ] }

  annotations.dummy_registry:
    class: Doctrine\Common\Annotations\AnnotationRegistry
    calls:
      - { method: registerLoader, arguments: [ class_exists ] }

  annotations.reader:
    class: Doctrine\Common\Annotations\AnnotationReader
    public: false
    calls:
      - method: addGlobalIgnoredName
        arguments:
          - required
          - '@annotations.dummy_registry'

  izi\prestashop\Twig\Loader\TemplateNameMappingLoader:
    class: izi\prestashop\Twig\Loader\TemplateNameMappingLoader
    public: false
    decorates: twig.loader
    arguments:
      - '@izi\prestashop\Twig\Loader\TemplateNameMappingLoader.inner'
      - bootstrap_4_layout.html.twig: bootstrap_3_layout.html.twig
        bootstrap_4_horizontal_layout.html.twig: bootstrap_3_horizontal_layout.html.twig
        '@PrestaShop/Admin/TwigTemplateForm/bootstrap_4_horizontal_layout.html.twig': '@@PrestaShop/Admin/TwigTemplateForm/bootstrap_3_horizontal_layout.html.twig'
