services:
  _defaults:
    public: false

  izi\prestashop\EventListener\CartListener:
    class: izi\prestashop\EventListener\CartListener
#    deprecated: ~
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@inpost.izi.context'
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\CommandBusInterface'
      - '@inpost.izi.logger'

  izi\prestashop\Cart\EventListener\UpdateBasketListener:
    class: izi\prestashop\Cart\EventListener\UpdateBasketListener
    tags:
      - kernel.event_subscriber
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@izi\prestashop\CommandBusInterface'
      - '@inpost.izi.logger'

  izi\prestashop\Handler\UpdateBasketHandlerInterface: '@izi\prestashop\Handler\UpdateBasketHandler'
  izi\prestashop\Handler\UpdateBasketHandler:
    class: izi\prestashop\Handler\UpdateBasketHandler
    tags:
      - inpost.izi.command_handler
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Basket\BasketBuilderFactory'
      - '@izi\prestashop\BasketApp\Basket\BasketsApiClientInterface'
      - '@inpost.izi.logger'

  izi\prestashop\Handler\UnbindBasketHandlerInterface: '@izi\prestashop\Handler\UnbindBasketHandler'
  izi\prestashop\Handler\UnbindBasketHandler:
    class: izi\prestashop\Handler\UnbindBasketHandler
    tags:
      - inpost.izi.command_handler
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\BasketApp\Basket\BasketsApiClientInterface'

  izi\prestashop\Builder\Basket\BasketBuilderFactory:
    class: izi\prestashop\Builder\Basket\BasketBuilderFactory
    arguments:
      - '@inpost.izi.clock'
      - '@izi\prestashop\ContextManager'
      - '@izi\prestashop\Configuration\ConsentsConfiguration'
      - '@izi\prestashop\Builder\Basket\DeliveryFactory'
      - '@izi\prestashop\Builder\Basket\ProductDeliveryFactory'
      - '@izi\prestashop\Product\Price\LowestPriceProviderInterface'
      - '@izi\prestashop\PromoCode\PromoCodeProviderInterface'
      - '@izi\prestashop\PromoCode\AvailablePromotionsProviderInterface'
      - '@inpost.izi.validator'

  izi\prestashop\Builder\Basket\DeliveryFactory:
    class: izi\prestashop\Builder\Basket\DeliveryFactory
    arguments:
      - '@izi\prestashop\Configuration\ShippingConfigurationInterface'
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'
      - '@inpost.izi.clock'
      - '@inpost.izi.translator'
      - '@izi\prestashop\Shipping\DeliveryPriceCalculator'
      - '@izi\prestashop\Configuration\PrestaShopConfiguration'

  izi\prestashop\Builder\Basket\ProductDeliveryFactory:
    class: izi\prestashop\Builder\Basket\ProductDeliveryFactory
    arguments:
      - '@izi\prestashop\Configuration\ShippingConfigurationInterface'
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'
      - '@izi\prestashop\Shipping\CartTotal\CartTotalDeliveryStrategyInterface'
      - '@izi\prestashop\Shipping\CartWeight\CartWeightDeliveryStrategyInterface'
      - '@izi\prestashop\Shipping\ProductDimensions\ProductDimensionsDeliveryStrategyInterface'
      - '@izi\prestashop\Shipping\ProductRestriction\ProductRestrictionDeliveryInterface'
