services:
  inpost.izi.db:
    class: Db
    public: false
    factory: [ Db, getInstance ]

  izi\prestashop\Database\Connection:
    class: izi\prestashop\Database\Connection
    public: true
    arguments:
      - '@inpost.izi.db'
    calls:
      - method: setLogger
        arguments:
          - '@inpost.izi.logger'
