parameters:
  inpost.izi.logs_dir: '%kernel.root_dir%/../var/logs/inpost'
  inpost.izi.logger_config:
    type: rotating_file
    path: '%inpost.izi.logs_dir%/izi.log'
    max_files: 14
    bubble: false
    channels: [ general, basket_app, merchant_api ]
    process_psr_3_messages:
      remove_used_context_fields: true
    include_stacktraces: true

  inpost.izi.deprecation_logger_config:
    type: rotating_file
    path: '%inpost.izi.logs_dir%/izi.deprecations.log'
    max_files: 3
    bubble: false
    channels: [ deprecation ]

services:
  inpost.izi.logger: '@inpost.izi.general_logger'
  inpost.izi.general_logger:
    class: Psr\Log\LoggerInterface
    public: true
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - general
      - '%inpost.izi.logger_config%'

  inpost.izi.basket_app_logger:
    class: Psr\Log\LoggerInterface
    public: false
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - basket_app
      - '%inpost.izi.logger_config%'

  # todo: make private after refactoring the front controller
  inpost.izi.merchant_api_logger:
    class: Psr\Log\LoggerInterface
    public: true
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - merchant_api
      - '%inpost.izi.logger_config%'

  inpost.izi.logger.deprecation:
    class: Psr\Log\LoggerInterface
    public: true # internal
    factory: [ '@izi\prestashop\Log\MonologLoggerFactory', create ]
    arguments:
      - deprecation
      - '%inpost.izi.deprecation_logger_config%'

  izi\prestashop\Log\MonologLoggerFactory:
    class: izi\prestashop\Log\MonologLoggerFactory
    public: false
    arguments:
      - !tagged inpost.izi.log_handler_factory

  izi\prestashop\Log\Handler\RotatingFileHandlerFactory:
    class: izi\prestashop\Log\Handler\RotatingFileHandlerFactory
    public: false
    tags:
      - { name: inpost.izi.log_handler_factory }
    arguments:
      - '@=service("izi\\prestashop\\Configuration\\AdvancedConfigurationInterface").isDebugEnabled() ? "dev" : "prod"'
