services:
  _defaults:
    public: false

  izi\prestashop\EventListener\OrderListener:
    class: izi\prestashop\EventListener\OrderListener
    tags:
      - kernel.event_subscriber
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@inpost.izi.object_model.order_repository'
      - '@izi\prestashop\CommandBusInterface'
      - '@inpost.izi.logger'

  izi\prestashop\EventListener\ShipmentListener:
    class: izi\prestashop\EventListener\ShipmentListener
    tags:
      - kernel.event_subscriber
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@izi\prestashop\ObjectModel\Repository\ShipmentRepository'
      - '@izi\prestashop\CommandBusInterface'
      - '@inpost.izi.logger'

  izi\prestashop\Mail\EventListener\ReplaceOrderNotificationRecipientListener:
    class: izi\prestashop\Mail\EventListener\ReplaceOrderNotificationRecipientListener
    tags:
      - kernel.event_subscriber
    arguments:
      - '@izi\prestashop\Mail\Resolver\OrderMailRecipientResolver'

  izi\prestashop\Mail\EventListener\AddDigitalDeliveryRecipientListener:
    class: izi\prestashop\Mail\EventListener\AddDigitalDeliveryRecipientListener
    tags:
      - kernel.event_subscriber
    arguments:
      - '@izi\prestashop\Repository\OrderDataRepositoryInterface'

  izi\prestashop\Repository\OrderDataRepositoryInterface:
    alias: izi\prestashop\Repository\BasketSessionRepository
    public: true

  izi\prestashop\Handler\UpdateOrderTrackingNumbersHandlerInterface: '@izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler'
  izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler:
    class: izi\prestashop\Handler\UpdateOrderTrackingNumbersHandler
    tags:
      - inpost.izi.command_handler
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Order\OrderEventBuilderFactory'
      - '@izi\prestashop\BasketApp\Order\OrdersApiClientInterface'
      - !tagged inpost.izi.tracking_number_provider

  izi\prestashop\Handler\UpdateOrderStatusHandlerInterface: '@izi\prestashop\Handler\UpdateOrderStatusHandler'
  izi\prestashop\Handler\UpdateOrderStatusHandler:
    class: izi\prestashop\Handler\UpdateOrderStatusHandler
    tags:
      - inpost.izi.command_handler
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Order\OrderEventBuilderFactory'
      - '@izi\prestashop\BasketApp\Order\OrdersApiClientInterface'
      - '@inpost.izi.logger'

  izi\prestashop\Handler\UpdateOrderAddressDeliveryHandlerInterface: '@izi\prestashop\Handler\UpdateOrderAddressDeliveryHandler'
  izi\prestashop\Handler\UpdateOrderAddressDeliveryHandler:
    class: izi\prestashop\Handler\UpdateOrderAddressDeliveryHandler
    tags:
      - inpost.izi.command_handler
    arguments:
      - '@izi\prestashop\Repository\BasketSessionRepository'
      - '@izi\prestashop\Builder\Order\OrderEventBuilderFactory'
      - '@izi\prestashop\BasketApp\Order\OrdersApiClientInterface'
      - '@izi\prestashop\Order\Address\AddressDataMapper'
      - '@izi\prestashop\ObjectModel\ObjectManager'

  izi\prestashop\Builder\Order\OrderEventBuilderFactory:
    class: izi\prestashop\Builder\Order\OrderEventBuilderFactory
    arguments:
      - '@inpost.izi.object_model.order_repository'
      - '@izi\prestashop\Builder\Order\OrderStatusDescriptionProvider'
      - '@inpost.izi.clock'

  izi\prestashop\Builder\Order\OrderStatusDescriptionProvider:
    class: izi\prestashop\Builder\Order\OrderStatusDescriptionProvider
    arguments:
      - '@inpost.izi.object_model.order_state_repository'
      - '@izi\prestashop\Configuration\OrdersConfiguration'

  izi\prestashop\Order\Message\MessageFormatterInterface: '@izi\prestashop\Order\Message\MessageFormatter'
  izi\prestashop\Order\Message\MessageFormatter:
    class: izi\prestashop\Order\Message\MessageFormatter
    arguments:
      - '@izi\prestashop\Order\Message\ParametersExtractorInterface'
      - !tagged inpost.izi.order_message_processor

  izi\prestashop\Order\Message\ParameterDescriptorInterface: '@izi\prestashop\Order\Message\ParametersExtractor'
  izi\prestashop\Order\Message\ParametersExtractorInterface: '@izi\prestashop\Order\Message\ParametersExtractor'
  izi\prestashop\Order\Message\ParametersExtractor:
    class: izi\prestashop\Order\Message\ParametersExtractor
    arguments:
      - '@inpost.izi.translator'

  izi\prestashop\Order\Message\Processor\ConditionalBlockProcessor:
    class: izi\prestashop\Order\Message\Processor\ConditionalBlockProcessor
    tags:
      - { name: inpost.izi.order_message_processor, priority: 100 }
    arguments:
      - '@izi\prestashop\Order\Message\ExpressionLanguage'

  izi\prestashop\Order\Message\Processor\ExpressionLanguageProcessor:
    class: izi\prestashop\Order\Message\Processor\ExpressionLanguageProcessor
    tags:
      - { name: inpost.izi.order_message_processor, priority: 50 }
    arguments:
      - '@izi\prestashop\Order\Message\ExpressionLanguage'

  izi\prestashop\Order\Message\Processor\ParameterReplacementProcessor:
    class: izi\prestashop\Order\Message\Processor\ParameterReplacementProcessor
    tags:
      - inpost.izi.order_message_processor

  izi\prestashop\Order\Message\ExpressionLanguage:
    class: izi\prestashop\Order\Message\ExpressionLanguage

  izi\prestashop\Order\Address\AddressDataMapper:
    class: izi\prestashop\Order\Address\AddressDataMapper

  izi\prestashop\Mail\Resolver\OrderMailRecipientResolver:
    class: izi\prestashop\Mail\Resolver\OrderMailRecipientResolver
    arguments:
      - '@izi\prestashop\Repository\OrderDataRepositoryInterface'
      - '@inpost.izi.object_model.order_repository'
