# config page configuration
imports:
  - { resource: services/common.yml }

services:
  izi\prestashop\CommandBus:
    class: izi\prestashop\CommandBus
    public: false
    autowire: true
    tags:
      - { name: container.service_subscriber }

  izi\prestashop\Controller\Admin\ConfigurationController:
    class: izi\prestashop\Controller\Admin\ConfigurationController
    public: false
    tags:
      - { name: controller.service_arguments }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'

  izi\prestashop\View\Asset\AssetManagerInterface: '@izi\prestashop\View\Asset\AdminAssetManager'
  izi\prestashop\View\Asset\AdminAssetManager:
    class: izi\prestashop\View\Asset\AdminAssetManager
    public: false
    arguments:
      - '@inpost.izi.module'
      - '@inpost.izi.context'

  izi\prestashop\Form\Type\GeneralConfigurationType:
    class: izi\prestashop\Form\Type\GeneralConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\ApiConfigurationType:
    class: izi\prestashop\Form\Type\ApiConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\EnvironmentChoiceType:
    class: izi\prestashop\Form\Type\EnvironmentChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\ClientCredentialsType:
    class: izi\prestashop\Form\Type\ClientCredentialsType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\MaskedPasswordType:
    class: izi\prestashop\Form\Type\MaskedPasswordType
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\OrdersConfigurationType:
    class: izi\prestashop\Form\Type\OrdersConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\OrderStateChoiceType:
    class: izi\prestashop\Form\Type\OrderStateChoiceType
    tags:
      - { name: form.type }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Form\ChoiceList\OrderStateChoiceLoader'

  izi\prestashop\Form\Type\ShippingConfigurationType:
    class: izi\prestashop\Form\Type\ShippingConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\AdvancedConfigurationType:
    class: izi\prestashop\Form\Type\AdvancedConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\CarrierChoiceType:
    class: izi\prestashop\Form\Type\Shipping\CarrierChoiceType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\Form\ChoiceList\CarrierChoiceLoader'

  izi\prestashop\Form\Type\Shipping\CarrierMappingsType:
    class: izi\prestashop\Form\Type\Shipping\CarrierMappingsType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\CarrierMappingType:
    class: izi\prestashop\Form\Type\Shipping\CarrierMappingType
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\OptionalServicesType:
    class: izi\prestashop\Form\Type\Shipping\OptionalServicesType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\ServiceOptionsType:
    class: izi\prestashop\Form\Type\Shipping\ServiceOptionsType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\ShippingOptionsType:
    class: izi\prestashop\Form\Type\Shipping\ShippingOptionsType
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\TimeOfWeekType:
    class: izi\prestashop\Form\Type\Shipping\TimeOfWeekType
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\TimeOfWeekRangeType:
    class: izi\prestashop\Form\Type\Shipping\TimeOfWeekRangeType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Shipping\WeekDayChoiceType:
    class: izi\prestashop\Form\Type\Shipping\WeekDayChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\OrderStatusDescriptionMapType:
    class: izi\prestashop\Form\Type\OrderStatusDescriptionMapType
    tags:
      - { name: form.type }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Form\ChoiceList\OrderStateChoiceLoader'

  izi\prestashop\Form\ChoiceList\OrderStateChoiceLoader:
    class: izi\prestashop\Form\ChoiceList\OrderStateChoiceLoader
    public: false
    arguments:
      - '@inpost.izi.object_model.order_state_repository'

  izi\prestashop\Form\ChoiceList\CarrierChoiceLoader:
    class: izi\prestashop\Form\ChoiceList\CarrierChoiceLoader
    public: false
    arguments:
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'

  izi\prestashop\Handler\Config\UpdateGeneralConfigurationHandlerInterface: '@izi\prestashop\Handler\Config\UpdateGeneralConfigurationHandler'
  izi\prestashop\Handler\Config\UpdateGeneralConfigurationHandler:
    class: izi\prestashop\Handler\Config\UpdateGeneralConfigurationHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@izi\prestashop\Configuration\OrdersConfigurationInterface'
      - '@izi\prestashop\Configuration\GeneralConfigurationInterface'
      - '@izi\prestashop\Cache\ConfigurationCache'

  izi\prestashop\Validator\InPostApiCredentialsValidator:
    class: izi\prestashop\Validator\InPostApiCredentialsValidator
    tags:
      - { name: validator.constraint_validator }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@izi\prestashop\BasketApp\AuthorizationProviderFactory'

  izi\prestashop\Validator\NotBlankInDefaultLanguageValidator:
    class: izi\prestashop\Validator\NotBlankInDefaultLanguageValidator
    tags:
      - { name: validator.constraint_validator }
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'

  izi\prestashop\Command\Config\UpdateGeneralConfigurationCommandFactory:
    class: izi\prestashop\Command\Config\UpdateGeneralConfigurationCommandFactory
    arguments:
      - '@izi\prestashop\Configuration\ApiConfigurationInterface'
      - '@izi\prestashop\Configuration\OrdersConfigurationInterface'
      - '@izi\prestashop\Configuration\GeneralConfigurationInterface'

  izi\prestashop\Form\Type\ConsentsConfigurationType:
    class: izi\prestashop\Form\Type\ConsentsConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Consent\ConsentType:
    class: izi\prestashop\Form\Type\Consent\ConsentType
    tags:
      - { name: form.type }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@inpost.izi.context'
      - '@izi\prestashop\ObjectModel\Repository\CmsPageRepository'

  izi\prestashop\Form\Type\Consent\ConsentRequirementChoiceType:
    class: izi\prestashop\Form\Type\Consent\ConsentRequirementChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Handler\Config\UpdateConsentsConfigurationHandlerInterface: '@izi\prestashop\Handler\Config\UpdateConsentsConfigurationHandler'
  izi\prestashop\Handler\Config\UpdateConsentsConfigurationHandler:
    class: izi\prestashop\Handler\Config\UpdateConsentsConfigurationHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@izi\prestashop\Configuration\ConsentsConfigurationInterface'
      - '@inpost.izi.clock'

  izi\prestashop\Form\Type\GuiConfigurationType:
    class: izi\prestashop\Form\Type\GuiConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\WidgetDisplayConfigurationType:
    class: izi\prestashop\Form\Type\Widget\WidgetDisplayConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\HtmlStylesType:
    class: izi\prestashop\Form\Type\Widget\HtmlStylesType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\WidgetConfigurationType:
    class: izi\prestashop\Form\Type\Widget\WidgetConfigurationType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\WidgetAlignmentChoiceType:
    class: izi\prestashop\Form\Type\Widget\WidgetAlignmentChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\WidgetVariantChoiceType:
    class: izi\prestashop\Form\Type\Widget\WidgetVariantChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\Type\Widget\WidgetFrameStyleChoiceType:
    class: izi\prestashop\Form\Type\Widget\WidgetFrameStyleChoiceType
    autowire: true
    tags:
      - { name: form.type }

  izi\prestashop\Form\TypeExtension\UnitTypeExtension:
    class: izi\prestashop\Form\TypeExtension\UnitTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\IntegerType }

  izi\prestashop\Form\TypeExtension\DateTimeImmutableTimeTypeExtension:
    class: izi\prestashop\Form\TypeExtension\DateTimeImmutableTimeTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TimeType }

  izi\prestashop\Form\TypeExtension\HelpTextExtension:
    class: izi\prestashop\Form\TypeExtension\HelpTextExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  izi\prestashop\Handler\Config\UpdateGuiConfigurationHandlerInterface: '@izi\prestashop\Handler\Config\UpdateGuiConfigurationHandler'
  izi\prestashop\Handler\Config\UpdateGuiConfigurationHandler:
    class: izi\prestashop\Handler\Config\UpdateGuiConfigurationHandler
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.command_handler }

  izi\prestashop\Handler\Config\UpdateShippingConfigurationHandlerInterface: '@izi\prestashop\Handler\Config\UpdateShippingConfigurationHandler'
  izi\prestashop\Handler\Config\UpdateShippingConfigurationHandler:
    class: izi\prestashop\Handler\Config\UpdateShippingConfigurationHandler
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.command_handler }

  izi\prestashop\Handler\Config\UpdateAdvancedConfigurationHandlerInterface: '@izi\prestashop\Handler\Config\UpdateAdvancedConfigurationHandler'
  izi\prestashop\Handler\Config\UpdateAdvancedConfigurationHandler:
    class: izi\prestashop\Handler\Config\UpdateAdvancedConfigurationHandler
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.command_handler }

  izi\prestashop\Handler\Config\CheckStatusHandlerInterface: '@izi\prestashop\Handler\Config\CheckStatusHandler'
  izi\prestashop\Handler\Config\CheckStatusHandler:
    class: izi\prestashop\Handler\Config\CheckStatusHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - !tagged inpost.izi.status_checker

  izi\prestashop\Handler\Config\DownloadModuleDataHandlerInterface: '@izi\prestashop\Handler\Config\DownloadModuleDataHandler'
  izi\prestashop\Handler\Config\DownloadModuleDataHandler:
    class: izi\prestashop\Handler\Config\DownloadModuleDataHandler
    public: false
    tags:
      - { name: inpost.izi.command_handler }
    arguments:
      - '@inpost.izi.module'
      - '@inpost.izi.context'
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'
      - '%inpost.izi.logs_dir%'

  izi\prestashop\Twig\Extension\LegacyTranslationExtension:
    class: izi\prestashop\Twig\Extension\LegacyTranslationExtension
    public: false
    tags:
      - { name: twig.extension }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'

  izi\prestashop\Handler\Config\Status\ConfigurationStatusChecker:
    class: izi\prestashop\Handler\Config\Status\ConfigurationStatusChecker
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.status_checker }

  izi\prestashop\Handler\Config\Status\DeliveryOptionsStatusChecker:
    class: izi\prestashop\Handler\Config\Status\DeliveryOptionsStatusChecker
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.status_checker }
    arguments:
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '@izi\prestashop\ObjectModel\Repository\CarrierRepository'

  izi\prestashop\Translation\LegacyTranslator:
    class: izi\prestashop\Translation\LegacyTranslator
    public: false
    arguments:
      - inpostizi

  izi\prestashop\Translation\ServiceNameTranslator:
    class: izi\prestashop\Translation\ServiceNameTranslator
    public: false
    autowire: true
